//! Hot-write Fastfetch config from colors.toml (Darwin + NixOS).

use std::path::{Path, PathBuf};

use crate::palette::load_palette;
use crate::state;

fn config_path() -> PathBuf {
    if let Ok(p) = std::env::var("DENDRITIC_FASTFETCH_LIVE") {
        return PathBuf::from(p);
    }
    state::home_dir()
        .map(|h| h.join(".config/fastfetch/config.jsonc"))
        .unwrap_or_else(|| PathBuf::from("config.jsonc"))
}

fn req<'a>(map: &'a std::collections::HashMap<String, String>, key: &str) -> Result<&'a str, String> {
    map.get(key)
        .map(String::as_str)
        .ok_or_else(|| format!("palette missing {key}"))
}

/// Write `~/.config/fastfetch/config.jsonc` with live logo/key colors.
pub fn write_live_from_colors(colors_path: &Path) -> Result<PathBuf, String> {
    let p = load_palette(colors_path)?;
    let b00 = req(&p, "base00")?;
    let b03 = req(&p, "base03")?;
    let b05 = req(&p, "base05")?;
    let b08 = req(&p, "base08")?;
    let b0a = req(&p, "base0A")?;
    let b0b = req(&p, "base0B")?;
    let b0c = req(&p, "base0C")?;
    let b0d = req(&p, "base0D")?;
    let b0e = req(&p, "base0E")?;

    let body = format!(
        r##"// Generated by dendritic-appearance from ~/.colors.toml — do not edit.
{{
  "logo": {{
    "type": "auto",
    "padding": {{
      "top": 1,
      "left": 1,
      "right": 2
    }},
    "color": {{
      "1": "{b0d}",
      "2": "{b0e}",
      "3": "{b0c}",
      "4": "{b0b}",
      "5": "{b0a}",
      "6": "{b08}",
      "7": "{b05}",
      "8": "{b00}",
      "9": "{b0d}"
    }}
  }},
  "display": {{
    "separator": "  ",
    "color": {{
      "keys": "{b0d}",
      "title": "{b0e}",
      "output": "{b05}",
      "separator": "{b03}"
    }}
  }},
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "terminal",
    "cpu",
    "memory",
    "disk",
    "break",
    "colors"
  ]
}}
"##
    );

    let dest = config_path();
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    if let Ok(existing) = std::fs::read_to_string(&dest) {
        if existing == body {
            return Ok(dest);
        }
    }
    let _ = std::fs::remove_file(&dest);
    std::fs::write(&dest, body).map_err(|e| format!("write {}: {e}", dest.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o644));
    }
    Ok(dest)
}

pub fn apply_from_colors(colors_path: &Path) -> Result<(), String> {
    let _ = write_live_from_colors(colors_path)?;
    Ok(())
}
