//! Hot-write Starship `starship.toml` palette from colors.toml.
//!
//! Stylix bakes `[palettes.base16]` at `nh switch`. Wallpaper / light-dark
//! rotation updates `~/.colors.toml` without rebuilding, so named Starship
//! colors (`blue`, `cyan`, …) stay stuck on the rebuild palette — typically
//! dark-on-dark after a light→dark wallpaper flip. Mirror Ghostty/Yazi.

use std::path::{Path, PathBuf};

use crate::palette::load_palette;
use crate::state;

fn config_path() -> PathBuf {
    if let Ok(p) = std::env::var("DENDRITIC_STARSHIP_LIVE") {
        return PathBuf::from(p);
    }
    state::home_dir()
        .map(|h| h.join(".config/starship.toml"))
        .unwrap_or_else(|| PathBuf::from("starship.toml"))
}

fn req<'a>(map: &'a std::collections::HashMap<String, String>, key: &str) -> Result<&'a str, String> {
    map.get(key)
        .map(String::as_str)
        .ok_or_else(|| format!("palette missing {key}"))
}

/// Write `~/.config/starship.toml` with live base16 palette.
///
/// Keeps the dendritic prompt layout; only the palette tracks wallpaper /
/// light-dark. Starship re-reads this file every prompt, so no shell signal.
pub fn write_live_from_colors(colors_path: &Path) -> Result<PathBuf, String> {
    let p = load_palette(colors_path)?;
    let b00 = req(&p, "base00")?;
    let b01 = req(&p, "base01")?;
    let b02 = req(&p, "base02")?;
    let b03 = req(&p, "base03")?;
    let b04 = req(&p, "base04")?;
    let b05 = req(&p, "base05")?;
    let b06 = req(&p, "base06")?;
    let b07 = req(&p, "base07")?;
    let b08 = req(&p, "base08")?;
    let b09 = req(&p, "base09")?;
    let b0a = req(&p, "base0A")?;
    let b0b = req(&p, "base0B")?;
    let b0c = req(&p, "base0C")?;
    let b0d = req(&p, "base0D")?;
    let b0e = req(&p, "base0E")?;
    let b0f = req(&p, "base0F")?;

    let body = format!(
        r##"# Generated by dendritic-appearance from ~/.colors.toml — do not edit.
# Live base16 palette (HM seeds once; wallpaper / light-dark overwrites).
add_newline = false
command_timeout = 1000
format = "$directory$git_branch$git_status$nix_shell$character"
palette = "base16"
scan_timeout = 100

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 3

[git_branch]
style = "bold purple"

[git_status]
style = "bold yellow"

[nix_shell]
style = "bold blue"

[palettes.base16]
base00 = "{b00}"
base01 = "{b01}"
base02 = "{b02}"
base03 = "{b03}"
base04 = "{b04}"
base05 = "{b05}"
base06 = "{b06}"
base07 = "{b07}"
base08 = "{b08}"
base09 = "{b09}"
base0A = "{b0a}"
base0B = "{b0b}"
base0C = "{b0c}"
base0D = "{b0d}"
base0E = "{b0e}"
base0F = "{b0f}"
base10 = "{b00}"
base11 = "{b00}"
base12 = "{b08}"
base13 = "{b0a}"
base14 = "{b0b}"
base15 = "{b0c}"
base16 = "{b0d}"
base17 = "{b0e}"
black = "{b00}"
blue = "{b0d}"
bright-black = "{b03}"
bright-blue = "{b0d}"
bright-cyan = "{b0c}"
bright-green = "{b0b}"
bright-magenta = "{b0e}"
bright-purple = "{b0e}"
bright-red = "{b08}"
bright-white = "{b07}"
bright-yellow = "{b0a}"
brown = "{b0f}"
cyan = "{b0c}"
green = "{b0b}"
magenta = "{b0e}"
orange = "{b09}"
purple = "{b0e}"
red = "{b08}"
white = "{b05}"
yellow = "{b0a}"
"##
    );

    let dest = config_path();
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    // Skip rewrite when unchanged (supervise poll).
    if let Ok(existing) = std::fs::read_to_string(&dest) {
        if existing == body {
            return Ok(dest);
        }
    }
    let _ = std::fs::remove_file(&dest);
    std::fs::write(&dest, body).map_err(|e| format!("write {}: {e}", dest.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o644));
    }
    Ok(dest)
}

pub fn apply_from_colors(colors_path: &Path) -> Result<(), String> {
    let _ = write_live_from_colors(colors_path)?;
    Ok(())
}
