//! Hot-write Yazi `theme.toml` from colors.toml (Darwin + NixOS).
//!
//! Stylix bakes a rebuild-time theme, but wallpaper rotation updates
//! `~/.colors.toml` without an `nh switch`. Mirror Ghostty: replace the HM
//! symlink with a live theme so Yazi stays readable against the terminal.

use std::path::{Path, PathBuf};

use crate::palette::load_palette;
use crate::state;

fn theme_path() -> PathBuf {
    if let Ok(p) = std::env::var("DENDRITIC_YAZI_LIVE") {
        return PathBuf::from(p);
    }
    state::home_dir()
        .map(|h| h.join(".config/yazi/theme.toml"))
        .unwrap_or_else(|| PathBuf::from("theme.toml"))
}

fn req<'a>(map: &'a std::collections::HashMap<String, String>, key: &str) -> Result<&'a str, String> {
    map.get(key)
        .map(String::as_str)
        .ok_or_else(|| format!("palette missing {key}"))
}

/// Write `~/.config/yazi/theme.toml` from colors.toml.
///
/// Sets `[mgr] overall.bg` (OSC 11) to base00 so the pane matches the live
/// wallpaper palette instead of inheriting a mismatched / washed-out look.
pub fn write_live_from_colors(colors_path: &Path) -> Result<PathBuf, String> {
    let p = load_palette(colors_path)?;
    let b00 = req(&p, "base00")?;
    let b01 = req(&p, "base01")?;
    let b02 = req(&p, "base02")?;
    let b03 = req(&p, "base03")?;
    let b04 = req(&p, "base04")?;
    let b05 = req(&p, "base05")?;
    let b08 = req(&p, "base08")?;
    let b09 = req(&p, "base09")?;
    let b0a = req(&p, "base0A")?;
    let b0b = req(&p, "base0B")?;
    let b0c = req(&p, "base0C")?;
    let b0d = req(&p, "base0D")?;
    let b0e = req(&p, "base0E")?;
    let b0f = req(&p, "base0F")?;

    let body = format!(
        r##"# Generated by dendritic-appearance from ~/.colors.toml — do not edit.
# Live base16 theme (HM seeds once; wallpaper rotation overwrites).

[mgr]
overall = {{ bg = "{b00}" }}
cwd = {{ fg = "{b0c}" }}
find_keyword = {{ fg = "{b0b}", bold = true }}
find_position = {{ fg = "{b0e}" }}
marker_copied = {{ fg = "{b0b}", bg = "{b0b}" }}
marker_cut = {{ fg = "{b08}", bg = "{b08}" }}
marker_selected = {{ fg = "{b0a}", bg = "{b0a}" }}
border_style = {{ fg = "{b04}" }}
count_copied = {{ fg = "{b00}", bg = "{b0b}" }}
count_cut = {{ fg = "{b00}", bg = "{b08}" }}
count_selected = {{ fg = "{b00}", bg = "{b0a}" }}

[indicator]
current = {{ bg = "{b02}", bold = true }}
preview = {{ bg = "{b02}", bold = true }}

[tabs]
active = {{ fg = "{b00}", bg = "{b0d}", bold = true }}
inactive = {{ fg = "{b0d}", bg = "{b01}" }}

[mode]
normal_main = {{ fg = "{b00}", bg = "{b0d}", bold = true }}
normal_alt = {{ fg = "{b0d}", bg = "{b00}" }}
select_main = {{ fg = "{b00}", bg = "{b0b}", bold = true }}
select_alt = {{ fg = "{b0b}", bg = "{b00}" }}
unset_main = {{ fg = "{b00}", bg = "{b0f}", bold = true }}
unset_alt = {{ fg = "{b0f}", bg = "{b00}" }}

[status]
overall = {{ bg = "{b01}", fg = "{b05}" }}
progress_label = {{ fg = "{b05}", bg = "{b00}" }}
progress_normal = {{ fg = "{b05}", bg = "{b00}" }}
progress_error = {{ fg = "{b08}", bg = "{b00}" }}
perm_type = {{ fg = "{b0d}" }}
perm_read = {{ fg = "{b0a}" }}
perm_write = {{ fg = "{b08}" }}
perm_exec = {{ fg = "{b0b}" }}
perm_sep = {{ fg = "{b0c}" }}

[pick]
border = {{ fg = "{b0d}" }}
active = {{ fg = "{b0e}" }}
inactive = {{ fg = "{b05}" }}

[input]
border = {{ fg = "{b0d}" }}
title = {{ fg = "{b05}" }}
value = {{ fg = "{b05}" }}
selected = {{ bg = "{b03}" }}

[completion]
border = {{ fg = "{b0d}" }}
active = {{ fg = "{b0e}", bg = "{b03}" }}
inactive = {{ fg = "{b05}" }}

[tasks]
border = {{ fg = "{b0d}" }}
title = {{ fg = "{b05}" }}
hovered = {{ fg = "{b05}", bg = "{b03}" }}

[which]
mask = {{ bg = "{b02}" }}
cand = {{ fg = "{b0c}" }}
rest = {{ fg = "{b0f}" }}
desc = {{ fg = "{b05}" }}
separator_style = {{ fg = "{b04}" }}

[help]
on = {{ fg = "{b0e}" }}
run = {{ fg = "{b0c}" }}
desc = {{ fg = "{b05}" }}
hovered = {{ fg = "{b05}", bg = "{b03}" }}
footer = {{ fg = "{b05}" }}

[[filetype.rules]]
mime = "image/*"
fg = "{b0c}"

[[filetype.rules]]
mime = "video/*"
fg = "{b0a}"

[[filetype.rules]]
mime = "audio/*"
fg = "{b0a}"

[[filetype.rules]]
mime = "application/zip"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/gzip"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/tar"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/bzip"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/bzip2"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/7z-compressed"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/rar"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/xz"
fg = "{b0e}"

[[filetype.rules]]
mime = "application/doc"
fg = "{b0b}"

[[filetype.rules]]
mime = "application/pdf"
fg = "{b0b}"

[[filetype.rules]]
mime = "application/rtf"
fg = "{b0b}"

[[filetype.rules]]
mime = "application/vnd.*"
fg = "{b0b}"

[[filetype.rules]]
url = "*/"
fg = "{b0d}"
bold = true

[[filetype.rules]]
mime = "*"
fg = "{b05}"

[[icon.conds]]
fg = "{b05}"
if = "orphan"
text = ""

[[icon.conds]]
fg = "{b04}"
if = "link"
text = ""

[[icon.conds]]
fg = "{b0a}"
if = "block"
text = ""

[[icon.conds]]
fg = "{b0a}"
if = "char"
text = ""

[[icon.conds]]
fg = "{b0a}"
if = "fifo"
text = ""

[[icon.conds]]
fg = "{b0a}"
if = "sock"
text = ""

[[icon.conds]]
fg = "{b0a}"
if = "sticky"
text = ""

[[icon.conds]]
fg = "{b08}"
if = "dummy"
text = ""

[[icon.conds]]
fg = "{b0d}"
if = "dir"
text = ""

[[icon.conds]]
fg = "{b0b}"
if = "exec"
text = ""

[[icon.conds]]
fg = "{b05}"
if = "!dir"
text = ""

[[icon.dirs]]
fg = "{b09}"
name = ".config"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = ".git"
text = ""

[[icon.dirs]]
fg = "{b0d}"
name = ".github"
text = ""

[[icon.dirs]]
fg = "{b0d}"
name = ".npm"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Desktop"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Development"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Documents"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Downloads"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Library"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Movies"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Music"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Pictures"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Public"
text = ""

[[icon.dirs]]
fg = "{b0c}"
name = "Videos"
text = ""
"##
    );

    let dest = theme_path();
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    let _ = std::fs::remove_file(&dest);
    std::fs::write(&dest, body).map_err(|e| format!("write {}: {e}", dest.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o644));
    }
    Ok(dest)
}

pub fn apply_from_colors(colors_path: &Path) -> Result<(), String> {
    let _ = write_live_from_colors(colors_path)?;
    Ok(())
}
