{ inputs, ... }:
{
  config = {
    # ── Darwin Specific Module ──────────────────────────────────
    flake.modules.darwin.microvm = { pkgs, inputs, ... }: {
      # NOTE: We do NOT use nix.linux-builder here because we use Determinate Nix.
      # Determinate Nix handles the Linux builder natively via determinate-nixd.
      
      environment.systemPackages = [ 
        # Tools to manage Determinate's native builder
        inputs.determinate-nix.packages.${pkgs.stdenv.hostPlatform.system}.default
        
        # The runner for MicroVMs, natively generated by the guest config
        inputs.self.nixosConfigurations.microvm.config.microvm.runner.vfkit
      ];
    };

    # ── NixOS Specific Module ───────────────────────────────────
    flake.modules.nixos.microvm = { pkgs, ... }: {
      environment.systemPackages = [ pkgs.microvm ];
    };

    # ── The MicroVM Definition ──────────────────────────────────
    flake.nixosConfigurations.microvm = 
      inputs.nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        modules = [
          { nixpkgs.hostPlatform = "aarch64-linux"; }
          inputs.microvm.nixosModules.microvm
          inputs.home-manager.nixosModules.home-manager
          
          # Dendritic host modules (system-level)
          inputs.self.modules.nixos.shell
          inputs.self.modules.nixos.styling
          
          ({ lib, pkgs, ... }: {
            networking.hostName = "dendritic-vm";
            services.getty.autologinUser = "root";
            
            microvm = {
              # On macOS, we use vfkit.
              hypervisor = "vfkit"; 
              vcpu = 2;
              mem = 2048;
              
              # CRITICAL: On Darwin hosts, we must disable systemd-machined registration
              # and provide the host's package set to build the runner correctly.
              registerWithMachined = false;
              vmHostPackages = inputs.nixpkgs.legacyPackages."aarch64-darwin";

              writableStoreOverlay = "/nix/.rw-store";
              volumes = [{
                image = "nix-store-overlay.img";
                mountPoint = "/nix/.rw-store";
                size = 10240;
              }];
              
              shares = [{
                tag = "ro-store";
                source = "/nix/store";
                mountPoint = "/nix/.ro-store";
                proto = "virtiofs";
              }];
            };

            # HM configuration for the VM
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.extraSpecialArgs = { inherit inputs; };
            home-manager.users.root = {
              imports = [
                inputs.self.modules.homeManager.shell
                inputs.self.modules.homeManager.editor
                inputs.self.modules.homeManager.styling
              ];
              home.stateVersion = "24.11";
            };

            nix.settings = {
              sandbox = false;
            };

            boot.initrd.systemd.enable = true;
            system.stateVersion = "25.11";
          })
        ];
      };
  };
}
