{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (config.colorScheme) palette;

  # Convert hex colors to RGB values for DiscordRecolor theme
  hexToRgb =
    hex:
    let
      # Strip the # prefix if present
      cleanHex = if builtins.substring 0 1 hex == "#" then builtins.substring 1 6 hex else hex;
      
      # Convert hex digit to decimal
      hexDigitToInt = d:
        if d == "0" then 0 else if d == "1" then 1 else if d == "2" then 2 else if d == "3" then 3
        else if d == "4" then 4 else if d == "5" then 5 else if d == "6" then 6 else if d == "7" then 7
        else if d == "8" then 8 else if d == "9" then 9 else if d == "a" || d == "A" then 10
        else if d == "b" || d == "B" then 11 else if d == "c" || d == "C" then 12
        else if d == "d" || d == "D" then 13 else if d == "e" || d == "E" then 14
        else if d == "f" || d == "F" then 15 else 0;
      
      # Convert two hex digits to decimal
      hexPairToInt = h1: h2: (hexDigitToInt h1) * 16 + (hexDigitToInt h2);
      
      r = hexPairToInt (builtins.substring 0 1 cleanHex) (builtins.substring 1 1 cleanHex);
      g = hexPairToInt (builtins.substring 2 1 cleanHex) (builtins.substring 3 1 cleanHex);
      b = hexPairToInt (builtins.substring 4 1 cleanHex) (builtins.substring 5 1 cleanHex);
    in
    "${toString r},${toString g},${toString b}";

  # Create DiscordRecolor theme using nix-colors palette
  discordRecolorTheme = ''
    /**
     * @name NixColors DiscordRecolor
     * @description Discord theme using nix-colors palette (${config.colorScheme.slug})
     * @author Generated by Nix
     * @version 1.0.0
     */

    @import url('https://mwittrien.github.io/BetterDiscordAddons/Themes/DiscordRecolor/DiscordRecolor.css');

    :root {
      /* Accent colors */
      --accentcolor: ${hexToRgb palette.base0D};              /* Primary accent (links, buttons) */
      --linkcolor: ${hexToRgb palette.base0D};                /* Link color */
      --mentioncolor: ${hexToRgb palette.base0A};             /* Mention highlight */
      
      /* Text colors */
      --textbrightest: ${hexToRgb palette.base07};            /* Brightest text */
      --textbrighter: ${hexToRgb palette.base06};             /* Brighter text */
      --textbright: ${hexToRgb palette.base05};               /* Normal text */
      --textdark: ${hexToRgb palette.base04};                 /* Darker text */
      --textdarker: ${hexToRgb palette.base03};               /* Even darker text */
      --textdarkest: ${hexToRgb palette.base02};              /* Darkest text */
      
      /* Background colors */
      --backgroundaccent: ${hexToRgb palette.base0D};         /* Accent backgrounds */
      --backgroundprimary: ${hexToRgb palette.base00};        /* Main background */
      --backgroundsecondary: ${hexToRgb palette.base01};      /* Secondary background */
      --backgroundsecondaryalt: ${hexToRgb palette.base01};   /* Alt secondary background */
      --backgroundtertiary: ${hexToRgb palette.base02};       /* Tertiary background */
      --backgroundfloating: ${hexToRgb palette.base01};       /* Floating elements */
      
      /* Status colors */
      --statusgreen: ${hexToRgb palette.base0B};              /* Online status */
      --statusyellow: ${hexToRgb palette.base0A};             /* Away status */
      --statusred: ${hexToRgb palette.base08};                /* DND/Error status */
      --statuspurple: ${hexToRgb palette.base0E};             /* Streaming status */
      
      /* Additional theme colors */
      --settingsicons: 1;                                     /* Enable settings icons */
    }
  '';
in
{
  programs.vesktop = {
    enable = true;

    # Vesktop-specific settings
    settings = {
      # Window settings
      minimizeToTray = true;
      startMinimized = false;

      # Performance settings
      hardwareAcceleration = true;

      # Privacy settings
      checkUpdates = false;
    };

    # Vencord configuration with nix-colors theming
    vencord = {
      # Use system Vencord to avoid conflicts
      useSystem = false;

      # Vencord settings
      settings = {
        # Enable useful plugins
        enabledThemes = [ "NixColors-DiscordRecolor.css" ];

        # Plugin configuration (all disabled by default)
        plugins = {
          # Core plugins
          BadgeAPI.enabled = false;
          CommandsAPI.enabled = false;
          ContextMenuAPI.enabled = false;
          MemberListDecoratorsAPI.enabled = false;
          MessageAccessoriesAPI.enabled = false;
          MessageDecorationsAPI.enabled = false;
          MessageEventsAPI.enabled = false;
          MessagePopoverAPI.enabled = false;
          NoticesAPI.enabled = false;
          ServerListAPI.enabled = false;
          SettingsStoreAPI.enabled = false;
          UserSettingsAPI.enabled = false;

          # Useful plugins
          AlwaysAnimate.enabled = false;
          BetterFolders.enabled = false;
          BetterGifAltText.enabled = false;
          BetterNotesBox.enabled = false;
          BetterRoleDot.enabled = false;
          BetterUploadButton.enabled = false;
          BiggerStreamPreview.enabled = false;
          BlurNSFW.enabled = false;
          CallTimer.enabled = false;
          ClearURLs.enabled = false;
          ClientTheme.enabled = false;
          ClientTheme.color = "#${palette.base0D}";
          ColorSighted.enabled = false;
          CrashHandler.enabled = false;
          EmoteCloner.enabled = false;
          Experiments.enabled = false;
          F8Break.enabled = false;
          FakeNitro.enabled = false;
          FavoriteEmojiFirst.enabled = false;
          FavoriteGifSearch.enabled = false;
          FixSpotifyEmbeds.enabled = false;
          FixYoutubeEmbeds.enabled = false;
          ForceOwnerCrown.enabled = false;
          FriendInvites.enabled = false;
          GameActivityToggle.enabled = false;
          GifPaste.enabled = false;
          GreetStickerPicker.enabled = false;
          HideAttachments.enabled = false;
          iLoveSpam.enabled = false;
          IgnoreActivities.enabled = false;
          ImageZoom.enabled = false;
          InvisibleChat.enabled = false;
          KeepCurrentChannel.enabled = false;
          LastFMRichPresence.enabled = false;
          LoadingQuotes.enabled = false;
          MemberCount.enabled = false;
          MessageClickActions.enabled = false;
          MessageLinkEmbeds.enabled = false;
          MessageLogger.enabled = false;
          MessageTags.enabled = false;
          MoreCommands.enabled = false;
          MoreKaomoji.enabled = false;
          MoreUserTags.enabled = false;
          Moyai.enabled = false;
          MutualGroupDMs.enabled = false;
          NoBlockedMessages.enabled = false;
          NoDevtoolsWarning.enabled = false;
          NoF1.enabled = false;
          NoMosaic.enabled = false;
          NoProfileThemes.enabled = false;
          NoRPC.enabled = false;
          NoReplyMention.enabled = false;
          NoScreensharePreview.enabled = false;
          NoSystemBadge.enabled = false;
          NoTypingAnimation.enabled = false;
          NoUnblockToJump.enabled = false;
          NormalizeMessageLinks.enabled = false;
          NotificationVolume.enabled = false;
          NSFWGateBypass.enabled = false;
          OnePingPerDM.enabled = false;
          oneko.enabled = false;
          OpenInApp.enabled = false;
          PermissionFreeWill.enabled = false;
          PermissionsViewer.enabled = false;
          PictureInPicture.enabled = false;
          PinDMs.enabled = false;
          PlainFolderIcon.enabled = false;
          PlatformIndicators.enabled = false;
          PreviewMessage.enabled = false;
          QuickMention.enabled = false;
          QuickReply.enabled = false;
          ReactErrorDecoder.enabled = false;
          ReadAllNotificationsButton.enabled = false;
          RelationshipNotifier.enabled = false;
          ReplaceGoogleSearch.enabled = false;
          ReplyTimestamp.enabled = false;
          RevealAllSpoilers.enabled = false;
          ReverseImageSearch.enabled = false;
          RoleColorEverywhere.enabled = false;
          SearchReply.enabled = false;
          SecretRingToneEnabler.enabled = false;
          Summaries.enabled = false;
          SendTimestamps.enabled = false;
          ServerListIndicators.enabled = false;
          ShikiCodeblocks.enabled = false;
          ShowAllMessageButtons.enabled = false;
          ShowConnections.enabled = false;
          ShowHiddenChannels.enabled = false;
          ShowMeYourName.enabled = false;
          ShowTimeouts.enabled = false;
          SilentMessageToggle.enabled = false;
          SilentTyping.enabled = false;
          SortFriendRequests.enabled = false;
          SpotifyControls.enabled = false;
          SpotifyCrack.enabled = false;
          SpotifyShareCommands.enabled = false;
          StartupTimings.enabled = false;
          SuperReactionTweaks.enabled = false;
          TextReplace.enabled = false;
          ThemeAttributes.enabled = false;
          TimeBarAllActivities.enabled = false;
          Translate.enabled = false;
          TypingIndicator.enabled = false;
          TypingTweaks.enabled = false;
          Unindent.enabled = false;
          UnsuppressEmbeds.enabled = false;
          UrbanDictionary.enabled = false;
          UserVoiceShow.enabled = false;
          USRBG.enabled = false;
          ValidUser.enabled = false;
          VoiceChatDoubleClick.enabled = false;
          VcNarrator.enabled = false;
          VencordToolbox.enabled = false;
          ViewIcons.enabled = false;
          ViewRaw.enabled = false;
          VoiceMessages.enabled = false;
          WebContextMenus.enabled = false;
          WebKeybinds.enabled = false;
          WebScreenShareFixes.enabled = false;
          WhoReacted.enabled = false;
          Wikisearch.enabled = false;
        };
      };

      # Custom themes with nix-colors integration
      themes = {
        "NixColors-DiscordRecolor.css" = discordRecolorTheme;
      };
    };
  };
}
