{pkgs, ...}:
# WireGuard VPN setup to access my homeserver from school.
{
  environment.systemPackages = with pkgs; [wireguard-tools];
  # TIP! Use:
  #wg genkey | tee privatekey | wg pubkey > publickey
  #to generate a key.

  networking.wg-quick.interfaces = {
    NIXSTATION64 = {
      # Host interface
      address = [
        # The IP addresses of the host.
        "192.168.1.21/24"
      ];
      peers = [
        # Peers linked to the host.
        {
          allowedIPs = [
            # Allowed IP addresses for the peer.
            "192.168.1.34/24"
          ];
          publicKey = "3w1nCIUCf70s3rSOrZEuv4Uy4/ND5TEoY6Ybz+SYg1M=";
        }
      ];
      privateKeyFile = "/private/privatekey"; # Private key file as generated by wg genkey.
      autostart = true; # Start the interface automatically on system boot.
    };

    NIXY = {
      # Peer interface
      address = [
        # The IP addresses of the peer.
        "192.168.1.34/24"
      ];
      peers = [
        # Peers linked to the peer.
        {
          allowedIPs = [
            # Allowed IP addresses for the host.
            "192.168.1.21/24" # Adjusted to /32 to specify a single IP address
          ];
          publicKey = "3w1nCIUCf70s3rSOrZEuv4Uy4/ND5TEoY6Ybz+SYg1M="; # Replace with the public key of NIXSTATION64.
          endpoint = "192.168.1.34/24"; # Specify the IP and port of NIXSTATION64.
        }
      ];
      privateKeyFile = "/private/privatekey"; # Private key file as generated by wg genkey.
      autostart = true; # Start the interface automatically on system boot.
    };
  };

  # Uncommented code placed at the bottom:

  # mtu = 1500; # The MTU is automatically determined from the endpoint addresses or the system default route.
  # listenPort = "51280"; # 16-bit port for listening. Optional; if not specified, automatically generated based on interface name.
  # dns = [ # The IP addresses of DNS servers to configure.
  #     "192.168.1.1"
  # ];
  # preUp = ""; # Commands called at the start of the interface setup.
  # preDown = ""; # Commands called before the interface is taken down.
  # postUp = ""; # Commands called after the interface setup.
  # postDown = ""; # Commands called after the interface is taken down.
  # table = null; # The kernel routing table to add this interface’s associated routes to.
  # peers.*.publicKey = ""; # The base64 public key to the peer.
  # peers.*.presharedKeyFile = ""; # File pointing to preshared key as generated by wg genpsk.
  # peers.*.persistentKeepalive = null; # In seconds from 1 to 65535 how often to send an authenticated empty packet to the peer.
  # peers.*.endpoint = ""; # Endpoint IP or hostname of the peer, followed by a colon, and then a port number of the peer.
}
