#!/bin/sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

# ACTIVE_SPACE=$(yabai -m query --spaces --space | jq '.index')
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

bar=(
  height=40
  corner_radius=10
  position=top
  color=$STATUS
  border_color=$GREY # why didn't that work?
  border_width=2
  y_offset=10
  sticky=off
  margin=13 # Margin around the bar
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.drawing=on
  # icon.font="Hack Nerd Font Mono:Regular:12.0"
  icon.color=$WHITE
  label.font="JetBrains Mono:Regular:12.0"
  label.drawing=on
  label.color=$WHITE
  popup.background.color=$TEMPUS
  popup.background.corner_radius=10
  popup.background.border_width=2
  popup.background.border_color=$PURPLE
  popup.y_offset=8
)

sketchybar --default "${defaults[@]}"

datetime=(
#FIXME: ONHOVER: https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-5328921
  background.color=$TEMPUS
  background.padding_left=3
  background.padding_right=3
  background.height=19
  background.corner_radius=10
  popup.horizontal=on # FIXME: FIGURE OUT HOW TO MAKE CALENDAR WITHOUT THIS!
  popup.align=center
  icon.padding_right=10
  icon.padding_left=10
  icon=$TIME
  icon.drawing=on
  label.padding_right=10
  update_freq=1
  script="$PLUGIN_DIR/datetime.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.height=135
  popup.width=10
  background.corner_radius=10
)

wifi=(
  script="$PLUGIN_DIR/wifi.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_right=10
  update_freq=2
  popup.align=center
)

battery=(
  script="$PLUGIN_DIR/battery.sh"
  update_freq=120
  updates=on
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_right=10
  popup.align=center
)

volume=(
  script="$PLUGIN_DIR/volume.sh"
  updates=on
  label.drawing=off
  icon.drawing=off
  slider.highlight_color=$GREY
  slider.background.height=5
  slider.background.corner_radius=3
  slider.background.color=$GREY
  slider.knob=$DOT
  slider.knob.drawing=off
  slider.padding_left=15
  slider.padding_right=15
  label.padding_right=10
  label.padding_left=10
  background.color=$STATUS
  background.height=10
  background.corner_radius=10
  background.border_width=2
  background.border_color=$GREY
  background.padding_right=7
)

volume_icon=(
  script="$PLUGIN_DIR/volume_icon.sh"
  #click_script="$PLUGIN_DIR/volume_click.sh"
  padding_right=10
  padding_left=10
)

mail=(
  # background.color=$TEMPUS
  background.height=25
  corner_radius=8
  padding_right=10
  icon.drawing=on
  icon="$MAIL"
  icon.padding_left=15
  script="$PLUGIN_DIR/mail.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  update_freq=60
)

cava=(
  update_freq=0
  script="$PLUGIN_DIR/cava.sh"
  label.drawing=on
  icon.drawing=off
  label="cava"
)

spotify=(
  click_script="$POPUP_CLICK_SCRIPT"
  popup.horizontal=on
  popup.align=center
  popup.height=100
  icon=$SPOTIFY
  icon.padding_right=15
  icon.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
  script="$PLUGIN_DIR/spotify.sh"
  update_freq=5
)

# spotify_label=(
#   label="Spotify"
#   label.padding_left=10
#   label.padding_right=15
#   label.font="JetBrains Mono:Bold:9.0"
#   script="$PLUGIN_DIR/spotify.sh"
#   update_freq=5
# )

ram=(
  icon=$RAM
  icon.padding_left=15
  script="$PLUGIN_DIR/ram.sh"
  label.padding_right=15
  label.padding_left=10
  update_freq=4
  background.corner_radius=10
  background.color=$TEMPUS
  background.height=19
  background.padding_left=-6
  background.padding_right=3
  background.border_color=$PURPLE
)

cpu=(
  icon=$CPU
  icon.padding_left=15
  script="$PLUGIN_DIR/cpu.sh"
  label.padding_left=10
  label.padding_right=15
  update_freq=4
)

apple=(
  script="$PLUGIN_DIR/apple.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label=$APPLE
  label.padding_right=15
  label.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
  popup.align=left
)

space_bg=(
  background.color=$SPACEBG
  background.height=19
  background.corner_radius=50
)

## Adding sketchybar Items:
# Left Items
sketchybar --add item apple left \
  --set apple "${apple[@]}"
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left \
  --set space.$sid space=$sid ignore_association=on \
    icon=${SPACE_ICONS[i]} \
    background.color=0x44ffffff \
    icon.highlight_color=0x00000000 \
    background.corner_radius=5 \
    padding_left=10 \
    padding_right=10 \
    background.height=20 \
    background.drawing=off \
    label.drawing=off \
    script="$PLUGIN_DIR/space.sh" \
    click_script="yabai -m space --focus $sid" \
    icon.font="JetBrains Mono:Regular:12.0"
done
sketchybar --add item separator_left left \
  --set separator_left "${active_app[@]}" \
    icon= \
    padding_left=10 \
    label.drawing=off \
    \
  --add item front_app left \
  --set front_app "${front_app[@]}" \
    script="$PLUGIN_DIR/front_app.sh" \
    icon.drawing=on \
    label.padding_left=15 \
    label.padding_right=15 \
    update_freq=5 \
  --subscribe front_app front_app_switched
sketchybar --add item active_app left \
   --set active_app "${active_app[@]}" \ 
   --subscribe front_app front_app_switched

# Center Items
sketchybar --add item volume_icon center \
  --set volume_icon "${volume_icon[@]}"
sketchybar --add slider volume center \
  --set volume "${volume[@]}" \
  --subscribe volume volume_change mouse.clicked mouse.entered mouse.exited
sketchybar --add item datetime center \
  --set datetime "${datetime[@]}" \
  --subscribe time system_woke
sketchybar --add item cava center \
  --set cava "${cava[@]}"
  # --add item spotify_label center \
  # --set spotify_label "${spotify_label[@]}"
sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify center \
  --set spotify "${spotify[@]}" \
  --subscribe spotify mouse.entered mouse.exited \
  mouse.exited.global

# Right Items
sketchybar --add item ram right \
  --set ram "${ram[@]}"
sketchybar --add item cpu right \
  --set cpu "${cpu[@]}"
sketchybar  --add item separator_right right \
  --set separator_right "${seperator_right[@]}" \
    icon= \
    padding_right=0 \
    label.drawing=off \
sketchybar --add item battery right \
  --set battery "${battery[@]}" \
  --subscribe battery power_source_change system_woke
rm -f /tmp/sketchybar_speed
rm -f /tmp/sketchybar_wifi
sketchybar --add item wifi right \
  --set wifi "${wifi[@]}" \
  --subscribe wifi system_woke
sketchybar --add item mail right \
  --set mail "${mail[@]}"

brackets=(
  background.color=$STATUS
  background.height=25
  background.corner_radius=20
  background.border_color=$PURPLE
  background.border_width=2
)

sketchybar --add bracket lbracket apple separator_left front_app left \
  --set lbracket "${brackets[@]}"
sketchybar --add bracket cbracket volume volume_icon datetime cava spotify center \
  --set cbracket "${brackets[@]}"
sketchybar --add bracket rbracket wifi battery separator_right mail ram cpu right \
  --set rbracket "${brackets[@]}"

sketchybar --update
