#!/bin/sh

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"
ACTIVE_SPACE=$(yabai -m query --spaces --space | jq '.index')
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

bar=(
  height=40
  corner_radius=10
  position=top
  color=$STATUS
  border_color=$GREY # why didn't that work?
  border_width=2
  y_offset=10
  sticky=off
  margin=13 # Margin around the bar
  notch_width=200
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.drawing=on
  icon.font="DejaVu Mono:Regular:12.0"
  icon.color=$WHITE
  label.font="DejaVu Mono:Regular:12.0"
  label.drawing=on
  label.color=$WHITE
  popup.background.color=$TEMPUS
  popup.background.corner_radius=10
  popup.background.border_width=2
  popup.background.border_color=$PURPLE
  popup.y_offset=8
)

sketchybar --default "${defaults[@]}"

datetime=(
#FIXME: ONHOVER: https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-5328921
  background.color=$TEMPUS
  background.padding_left=3
  background.padding_right=3
  background.height=19
  background.corner_radius=10
  popup.horizontal=on
  popup.align=center
  icon.padding_right=10
  icon.padding_left=10
  label.padding_right=10
  update_freq=1
  script="$PLUGIN_DIR/date.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  popup.height=140
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
)

wifi=(
  script="$PLUGIN_DIR/wifi.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_right=15
  update_freq=60
  popup.align=right
)

battery=(
  script="$PLUGIN_DIR/battery.sh"
  update_freq=120
  updates=on
  click_script="$POPUP_CLICK_SCRIPT"
  label.padding_left=15
  popup.align=right
)

volume=(
  script="$PLUGIN_DIR/volume.sh"
  updates=on
  label.drawing=off
  icon.drawing=off
  slider.highlight_color=$GREY
  slider.background.height=5
  slider.background.corner_radius=3
  slider.background.color=$GREY
  slider.knob=$DOT
  slider.knob.drawing=off
  slider.padding_left=15
  slider.padding_right=15
  label.padding_right=10
  label.padding_left=10
  background.color=$STATUS
  background.height=10
  background.corner_radius=10
  background.border_width=2
  background.border_color=$GREY
  background.padding_right=7
)

volume_icon=(
  script="$PLUGIN_DIR/volume_icon.sh"
  #click_script="$PLUGIN_DIR/volume_click.sh"
  label.padding_right=10
  label.padding_left=10
)

mail=(
  background.color=$TEMPUS
  background.height=25
  background.corner_radius=10
  background.padding_right=10
  background.border_color=$GREY
  background.border_width=2
  script="$PLUGIN_DIR/mail.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  icon.padding_left=15
  icon.padding_right=15
  update_freq=60
)

spotify=(
  click_script="$POPUP_CLICK_SCRIPT"
  popup.horizontal=on
  popup.align=center
  popup.height=100
  icon=$SPOTIFY
  icon.padding_right=15
  icon.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
  script="$PLUGIN_DIR/spotify.sh"
  update_freq=5
)

spotify_label=(
  label="Spotify"
  label.padding_left=10
  label.padding_right=15
  label.font="DejaVu Mono:Bold:9.0"
  script="$PLUGIN_DIR/spotify.sh"
  update_freq=5
)

ram=(
  icon=$RAM
  icon.padding_left=15
  script="$PLUGIN_DIR/ram.sh"
  label.padding_right=15
  label.padding_left=10
  update_freq=60
  background.corner_radius=10
  background.color=$TEMPUS
  background.height=19
  background.padding_left=-6
  background.padding_right=3
  background.border_color=$PURPLE
)

cpu=(
  icon=$CPU
  icon.padding_left=15
  script="$PLUGIN_DIR/cpu.sh"
  label.padding_left=10
  label.padding_right=15
  update_freq=60
)

apple=(
  script="$PLUGIN_DIR/apple.sh"
  click_script="$POPUP_CLICK_SCRIPT"
  label=$APPLE
  label.padding_right=15
  label.padding_left=15
  background.color=$TEMPUS
  background.height=19
  background.corner_radius=10
  background.padding_left=3
  background.padding_right=3
  popup.align=left
)

space=(
  script="$PLUGIN_DIR/spaces.sh"
  label.drawing=on
  #icon.drawing=on
  icon.padding_left=15
  icon.padding_right=15
  update_freq=1
)

space_bg=(
  background.color=$SPACEBG
  background.height=19
  background.corner_radius=50
)

CURRENT_APP_IN_SPACE=$(osascript -e 'tell application "System Events" to get name of first application process whose frontmost is true')
active_app=(
  icon.padding_left=15
  icon.padding_right=15
  background.color=$TEMPUS
  background.height=25
  background.corner_radius=10
  background.border_color=$PURPLE
  background.border_width=2
  label="$CURRENT_APP_IN_SPACE"
)

## Adding sketchybar Items:
# Left Items
sketchybar --add item apple left \
  --set apple "${apple[@]}"
declare -a spacesArray=()
for i in "${!SPACE_ICONS[@]}"; do
  sid=$(($i + 1))

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    CURRENT_ICON=$PACMAN
  else
    CURRENT_ICON=${SPACE_ICONS["$i"]}
  fi

  spacesArray+=("space.$sid")

  sketchybar --add space space.$sid left \
    --set space.$sid associated_space=$sid \
    icon="$CURRENT_ICON" \
    click_script="yabai -m space --focus $sid" \
    "${space[@]}"

  if [[ $sid -eq $ACTIVE_SPACE ]]; then
    sketchybar --set space.$sid "${space_bg[@]}"
  fi
done
sketchybar --add item active_app left \
  --set active_app "${active_app[@]}"

# Center Items

sketchybar --add item volume_icon center \
  --set volume_icon "${volume_icon[@]}"
sketchybar --add slider volume center \
  --set volume "${volume[@]}" \
  --subscribe volume volume_change mouse.clicked mouse.entered mouse.exited
sketchybar --add item datetime center \
  --set datetime "${datetime[@]}" \
  --subscribe time system_woke
sketchybar --add item spotify_label center \
  --set spotify_label "${spotify_label[@]}"
sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify center \
  --set spotify "${spotify[@]}" \
  --subscribe spotify mouse.entered mouse.exited \
  mouse.exited.global
# Right Items
sketchybar --add item ram right \
  --set ram "${ram[@]}"
sketchybar --add item cpu right \
  --set cpu "${cpu[@]}"
sketchybar --add item battery right \
  --set battery "${battery[@]}" \
  --subscribe battery power_source_change system_woke
rm -f /tmp/sketchybar_speed
rm -f /tmp/sketchybar_wifi
sketchybar --add item wifi right \
  --set wifi "${wifi[@]}" \
  --subscribe wifi system_woke
sketchybar --add item mail right \
  --set mail "${mail[@]}"

brackets=(
  background.color=$STATUS
  background.height=25
  background.corner_radius=20
  background.border_color=$PURPLE
  background.border_width=2
)

sketchybar --add bracket lbracket apple "${spacesArray[@]}" left \
  --set lbracket "${brackets[@]}"
sketchybar --add bracket cbracket volume volume_icon datetime spotify center \
  --set cbracket "${brackets[@]}"
sketchybar --add bracket rbracket ram cpu right \
  --set rbracket "${brackets[@]}"

sketchybar --update
