{
  flake.modules.homeManager.dendritic =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      cfg = config.dendritic.apps.jetbrains;
      c = config.lib.stylix.colors;
      fontName = config.stylix.fonts.monospace.name;
      fontSize = toString config.stylix.fonts.sizes.applications;
      isLight = config.dendritic.theme.variant == "light";
      parentScheme = if isLight then "Default" else "Darcula";
      lafClass =
        if isLight then
          "com.intellij.ide.ui.laf.IntelliJLaf"
        else
          "com.intellij.ide.ui.laf.darcula.DarculaLaf";
      lafThemeId = if isLight then "JetBrainsLightTheme" else "Darcula";

      # ── JetBrains .icls color scheme (inherits from Darcula) ─────
      iclsFile = pkgs.writeText "Stylix.icls" ''
        <scheme name="Stylix" version="142" parent_scheme="${parentScheme}">
          <metaInfo>
            <property name="created">Generated by Nix/Stylix</property>
          </metaInfo>
          <colors>
            <option name="ADDED_LINES_COLOR" value="${c.base0B}"/>
            <option name="CARET_COLOR" value="${c.base05}"/>
            <option name="CARET_ROW_COLOR" value="${c.base01}"/>
            <option name="CONSOLE_BACKGROUND_KEY" value="${c.base00}"/>
            <option name="DELETED_LINES_COLOR" value="${c.base08}"/>
            <option name="GUTTER_BACKGROUND" value="${c.base00}"/>
            <option name="INDENT_GUIDE" value="${c.base02}"/>
            <option name="LINE_NUMBERS_COLOR" value="${c.base03}"/>
            <option name="LINE_NUMBER_ON_CARET_ROW_COLOR" value="${c.base04}"/>
            <option name="MODIFIED_LINES_COLOR" value="${c.base0A}"/>
            <option name="NOTIFICATION_BACKGROUND" value="${c.base01}"/>
            <option name="RIGHT_MARGIN_COLOR" value="${c.base01}"/>
            <option name="SELECTION_BACKGROUND" value="${c.base02}"/>
            <option name="SELECTION_FOREGROUND" value="${c.base05}"/>
            <option name="SELECTED_TEARLINE_COLOR" value="${c.base03}"/>
            <option name="TEARLINE_COLOR" value="${c.base02}"/>
            <option name="WHITESPACES" value="${c.base03}"/>
          </colors>
          <attributes>
            <option name="TEXT">
              <value>
                <option name="FOREGROUND" value="${c.base05}"/>
                <option name="BACKGROUND" value="${c.base00}"/>
              </value>
            </option>

            <!-- Keywords & Control Flow -->
            <option name="DEFAULT_KEYWORD">
              <value>
                <option name="FOREGROUND" value="${c.base0E}"/>
                <option name="FONT_TYPE" value="1"/>
              </value>
            </option>

            <!-- Strings -->
            <option name="DEFAULT_STRING">
              <value><option name="FOREGROUND" value="${c.base0B}"/></value>
            </option>
            <option name="DEFAULT_VALID_STRING_ESCAPE">
              <value><option name="FOREGROUND" value="${c.base0C}"/></value>
            </option>
            <option name="DEFAULT_INVALID_STRING_ESCAPE">
              <value>
                <option name="FOREGROUND" value="${c.base08}"/>
                <option name="EFFECT_TYPE" value="1"/>
              </value>
            </option>

            <!-- Numbers & Constants -->
            <option name="DEFAULT_NUMBER">
              <value><option name="FOREGROUND" value="${c.base09}"/></value>
            </option>
            <option name="DEFAULT_CONSTANT">
              <value><option name="FOREGROUND" value="${c.base09}"/></value>
            </option>

            <!-- Comments -->
            <option name="DEFAULT_LINE_COMMENT">
              <value>
                <option name="FOREGROUND" value="${c.base03}"/>
                <option name="FONT_TYPE" value="2"/>
              </value>
            </option>
            <option name="DEFAULT_BLOCK_COMMENT">
              <value>
                <option name="FOREGROUND" value="${c.base03}"/>
                <option name="FONT_TYPE" value="2"/>
              </value>
            </option>
            <option name="DEFAULT_DOC_COMMENT">
              <value>
                <option name="FOREGROUND" value="${c.base03}"/>
                <option name="FONT_TYPE" value="2"/>
              </value>
            </option>
            <option name="DEFAULT_DOC_COMMENT_TAG">
              <value>
                <option name="FOREGROUND" value="${c.base0E}"/>
                <option name="FONT_TYPE" value="1"/>
              </value>
            </option>
            <option name="DEFAULT_DOC_COMMENT_TAG_VALUE">
              <value><option name="FOREGROUND" value="${c.base04}"/></value>
            </option>
            <option name="DEFAULT_DOC_MARKUP">
              <value><option name="FOREGROUND" value="${c.base04}"/></value>
            </option>

            <!-- Identifiers -->
            <option name="DEFAULT_IDENTIFIER">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_CLASS_NAME">
              <value><option name="FOREGROUND" value="${c.base0A}"/></value>
            </option>
            <option name="DEFAULT_CLASS_REFERENCE">
              <value><option name="FOREGROUND" value="${c.base0A}"/></value>
            </option>
            <option name="DEFAULT_INTERFACE_NAME">
              <value><option name="FOREGROUND" value="${c.base0A}"/></value>
            </option>
            <option name="DEFAULT_FUNCTION_DECLARATION">
              <value><option name="FOREGROUND" value="${c.base0D}"/></value>
            </option>
            <option name="DEFAULT_FUNCTION_CALL">
              <value><option name="FOREGROUND" value="${c.base0D}"/></value>
            </option>
            <option name="DEFAULT_INSTANCE_METHOD">
              <value><option name="FOREGROUND" value="${c.base0D}"/></value>
            </option>
            <option name="DEFAULT_STATIC_METHOD">
              <value><option name="FOREGROUND" value="${c.base0D}"/></value>
            </option>
            <option name="DEFAULT_INSTANCE_FIELD">
              <value><option name="FOREGROUND" value="${c.base08}"/></value>
            </option>
            <option name="DEFAULT_STATIC_FIELD">
              <value><option name="FOREGROUND" value="${c.base09}"/></value>
            </option>
            <option name="DEFAULT_LOCAL_VARIABLE">
              <value><option name="FOREGROUND" value="${c.base08}"/></value>
            </option>
            <option name="DEFAULT_PARAMETER">
              <value><option name="FOREGROUND" value="${c.base08}"/></value>
            </option>
            <option name="DEFAULT_GLOBAL_VARIABLE">
              <value><option name="FOREGROUND" value="${c.base08}"/></value>
            </option>

            <!-- Annotations & Metadata -->
            <option name="DEFAULT_METADATA">
              <value><option name="FOREGROUND" value="${c.base0E}"/></value>
            </option>
            <option name="DEFAULT_PREDEFINED_SYMBOL">
              <value><option name="FOREGROUND" value="${c.base0C}"/></value>
            </option>
            <option name="DEFAULT_LABEL">
              <value><option name="FOREGROUND" value="${c.base0C}"/></value>
            </option>
            <option name="DEFAULT_TEMPLATE_LANGUAGE_COLOR">
              <value><option name="FOREGROUND" value="${c.base0F}"/></value>
            </option>

            <!-- Operators & Punctuation -->
            <option name="DEFAULT_OPERATION_SIGN">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_BRACES">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_BRACKETS">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_PARENTHS">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_DOT">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_COMMA">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>
            <option name="DEFAULT_SEMICOLON">
              <value><option name="FOREGROUND" value="${c.base05}"/></value>
            </option>

            <!-- Errors & Warnings -->
            <option name="ERRORS_ATTRIBUTES">
              <value>
                <option name="EFFECT_COLOR" value="${c.base08}"/>
                <option name="EFFECT_TYPE" value="2"/>
              </value>
            </option>
            <option name="WARNING_ATTRIBUTES">
              <value>
                <option name="EFFECT_COLOR" value="${c.base0A}"/>
                <option name="EFFECT_TYPE" value="2"/>
              </value>
            </option>
            <option name="DEPRECATED_ATTRIBUTES">
              <value>
                <option name="EFFECT_COLOR" value="${c.base03}"/>
                <option name="EFFECT_TYPE" value="3"/>
              </value>
            </option>

            <!-- TODO / Bookmarks -->
            <option name="TODO_DEFAULT_ATTRIBUTES">
              <value>
                <option name="FOREGROUND" value="${c.base0A}"/>
                <option name="FONT_TYPE" value="3"/>
              </value>
            </option>

            <!-- Search results -->
            <option name="SEARCH_RESULT_ATTRIBUTES">
              <value>
                <option name="BACKGROUND" value="${c.base02}"/>
              </value>
            </option>
            <option name="WRITE_SEARCH_RESULT_ATTRIBUTES">
              <value>
                <option name="BACKGROUND" value="${c.base02}"/>
              </value>
            </option>

            <!-- Diff -->
            <option name="DIFF_MODIFIED">
              <value><option name="BACKGROUND" value="${c.base01}"/></value>
            </option>
            <option name="DIFF_INSERTED">
              <value><option name="BACKGROUND" value="${c.base01}"/></value>
            </option>
            <option name="DIFF_DELETED">
              <value><option name="BACKGROUND" value="${c.base01}"/></value>
            </option>
          </attributes>
        </scheme>
      '';

      # ── Options XMLs ─────────────────────────────────────────────
      colorSchemeXml = pkgs.writeText "colors.scheme.xml" ''
        <application>
          <component name="EditorColorsManagerImpl">
            <global_color_scheme name="Stylix" />
          </component>
        </application>
      '';

      editorFontXml = pkgs.writeText "editor-font.xml" ''
        <application>
          <component name="DefaultFont">
            <option name="FONT_FAMILY" value="${fontName}"/>
            <option name="FONT_SIZE" value="${fontSize}"/>
            <option name="FONT_REGULAR_WEIGHT" value="400"/>
            <option name="VERSION" value="1"/>
          </component>
        </application>
      '';

      consoleFontXml = pkgs.writeText "console-font.xml" ''
        <application>
          <component name="ConsoleFont">
            <option name="FONT_FAMILY" value="${fontName}"/>
            <option name="FONT_SIZE" value="${fontSize}"/>
            <option name="VERSION" value="1"/>
          </component>
        </application>
      '';

      terminalFontXml = pkgs.writeText "terminal-font.xml" ''
        <application>
          <component name="TerminalFontOptions">
            <option name="FONT_FAMILY" value="${fontName}"/>
            <option name="FONT_SIZE" value="${fontSize}"/>
            <option name="VERSION" value="1"/>
          </component>
        </application>
      '';

      keymapXml = pkgs.writeText "keymap.xml" ''
        <application>
          <component name="KeymapManager">
            <active_keymap name="VSCode" />
          </component>
        </application>
      '';

      lafXml = pkgs.writeText "laf.xml" ''
        <application>
          <component name="LafManager" autodetect="false">
            <laf class-name="${lafClass}" themeId="${lafThemeId}" />
          </component>
        </application>
      '';

      googleJavaFormatXml = pkgs.writeText "google-java-format.xml" ''
        <application>
          <component name="GoogleJavaFormatSettings">
            <option name="enabled" value="true" />
            <option name="style" value="GOOGLE" />
          </component>
        </application>
      '';

      # ── Trust all projects under $HOME ────────────────────────────
      # Silences the "Trust Project?" dialog for all JetBrains IDEs.
      trustedLocationsXml = pkgs.writeText "trusted-locations.xml" ''
        <application>
          <component name="Trusted.Paths">
            <option name="TRUST_ALL_PROJECTS" value="true" />
            <option name="TRUSTED_PATHS">
              <list>
                <option value="$USER_HOME$" />
              </list>
            </option>
            <option name="TRUSTED_PROJECTS_ROOTS">
              <list />
            </option>
          </component>
        </application>
      '';

      # Directories to skip (not actual IDE products)
      skipDirs = "Daemon|Local|consentOptions|bl|crl";
    in
    {
      options.dendritic.apps.jetbrains = {
        enable = lib.mkEnableOption "JetBrains IDE theming via Stylix";
      };

      config = lib.mkIf cfg.enable {
        # JetBrains IDE packages, gated by this module's enable toggle so
        # the HM-managed binaries match the dock entries declared in the
        # Darwin half below.
        home.packages = with pkgs; [
          jetbrains.clion
          jetbrains.idea
          jetbrains.rust-rover
        ];

        # Auto-discover all JetBrains product directories and deploy theme files.
        # Handles both macOS (~/Library/...) and Linux (~/.config/...) paths.
        home.activation.jetbrainsTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          if [ "$OSTYPE" == "darwin"* ]; then
            JB_BASE="$HOME/Library/Application Support/JetBrains"
          else
            JB_BASE="$HOME/.config/JetBrains"
          fi

          if [ -d "$JB_BASE" ]; then
            for product_dir in "$JB_BASE"/*/; do
              [ ! -d "$product_dir" ] && continue
              case "$(basename "$product_dir")" in
                ${skipDirs}) continue ;;
              esac

              # Color scheme
              $DRY_RUN_CMD mkdir -p "$product_dir/colors"
              $DRY_RUN_CMD cp -f "${iclsFile}" "$product_dir/colors/Stylix.icls"

              # Options
              $DRY_RUN_CMD mkdir -p "$product_dir/options"
              $DRY_RUN_CMD cp -f "${colorSchemeXml}" "$product_dir/options/colors.scheme.xml"
              $DRY_RUN_CMD cp -f "${editorFontXml}" "$product_dir/options/editor-font.xml"
              $DRY_RUN_CMD cp -f "${consoleFontXml}" "$product_dir/options/console-font.xml"
              $DRY_RUN_CMD cp -f "${terminalFontXml}" "$product_dir/options/terminal-font.xml"
              $DRY_RUN_CMD cp -f "${keymapXml}" "$product_dir/options/keymap.xml"
              $DRY_RUN_CMD cp -f "${lafXml}" "$product_dir/options/laf.xml"
              $DRY_RUN_CMD cp -f "${googleJavaFormatXml}" "$product_dir/options/google-java-format.xml"
              # Disable the Trust Project dialog
              $DRY_RUN_CMD cp -f "${trustedLocationsXml}" "$product_dir/options/trusted-locations.xml"
            done
          fi
        '';

        # Set JAVA_HOME so JetBrains IDEs can find the Nix-managed JDK
        programs.java = {
          enable = true;
          package = pkgs.jdk21;
        };
      };
    };

  # Dock registration: JetBrains IDEs own their dock entries (order 150 in `dock.nix`).
  flake.modules.darwin.dendritic =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      user = config.system.primaryUser;
      jetbrainsEnabled = config.home-manager.users.${user}.dendritic.apps.jetbrains.enable or false;
    in
    lib.mkIf jetbrainsEnabled {
      dendritic.dock.apps = lib.mkOrder 150 [
        "${pkgs.jetbrains.idea}/Applications/IntelliJ IDEA.app"
        "${pkgs.jetbrains.clion}/Applications/CLion.app"
        "${pkgs.jetbrains.rust-rover}/Applications/RustRover.app"
      ];
    };
}
