# ── Dendritic macrdp (macOS RDP server) ─────────────────────────────────
#
# Packages https://github.com/x6nux/macrdp and runs it as a GUI-session
# agent on an unprivileged port, with:
#   • root socat forward 3389 → listenPort  (mba.local works without :port)
#   • dns-sd Bonjour `_rdp._tcp` on 3389   (zero-IP discovery from iPhone)
#
# Credentials: SecretSpec `MACRDP_PASSWORD` → ~/.config/macrdp/config.toml
# (never in the Nix store). Username defaults to the HM username.
#
# First-run TCC: grant Screen Recording + Accessibility to `macrdp-server`
# (System Settings → Privacy & Security).
{
  flake.modules.darwin.dendritic =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      cfg = config.dendritic.apps.macrdp;
      macrdp = pkgs.callPackage ./macrdp/_package.nix { };
      publicPort = cfg.publicPort;
      socatFwd = pkgs.writeShellScript "macrdp-portfwd" ''
        exec ${lib.getExe pkgs.socat} \
          TCP-LISTEN:${toString publicPort},bind=0.0.0.0,fork,reuseaddr \
          TCP:127.0.0.1:${toString cfg.listenPort}
      '';
    in
    {
      options.dendritic.apps.macrdp = {
        enable = lib.mkEnableOption "macrdp RDP server + Bonjour (_rdp._tcp)";

        listenPort = lib.mkOption {
          type = lib.types.port;
          default = 13389;
          description = "Unprivileged port macrdp binds as the logged-in user.";
        };

        publicPort = lib.mkOption {
          type = lib.types.port;
          default = 3389;
          description = "LAN-facing port (socat forward + Bonjour advertisement).";
        };

        bonjourName = lib.mkOption {
          type = lib.types.str;
          default = config.networking.hostName or "mba";
          description = "DNS-SD instance name shown in Bonjour browsers.";
        };
      };

      config = lib.mkIf cfg.enable {
        environment.systemPackages = [
          macrdp
          pkgs.socat
        ]
        ++ lib.optionals (pkgs.stdenv.hostPlatform.isLinux) [ pkgs.freerdp ];

        # RDP replaces Screen Sharing / VNC — keep the classic VNC daemon off.
        system.activationScripts.disableScreenSharing.text = ''
          echo "dendritic.macrdp: disabling com.apple.screensharing (VNC)"
          launchctl bootout system/com.apple.screensharing 2>/dev/null || true
          launchctl disable system/com.apple.screensharing 2>/dev/null || true
        '';

        # Privileged bind for standard RDP port → user agent.
        launchd.daemons.macrdp-portfwd = {
          serviceConfig = {
            Label = "com.aspaulding.macrdp-portfwd";
            ProgramArguments = [ "${socatFwd}" ];
            RunAtLoad = true;
            KeepAlive = true;
            StandardOutPath = "/var/log/macrdp-portfwd.log";
            StandardErrorPath = "/var/log/macrdp-portfwd.err.log";
          };
        };
      };
    };

  flake.modules.homeManager.dendritic =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    let
      cfg = config.dendritic.apps.macrdp;
      macrdp = pkgs.callPackage ./macrdp/_package.nix { };
      secretspecToml = ../../home/secretspec.toml;
      bonjourName = cfg.bonjourName;
      publicPort = cfg.publicPort;
      dnsSd = pkgs.writeShellScript "macrdp-bonjour" ''
        exec /usr/bin/dns-sd -R ${lib.escapeShellArg bonjourName} _rdp._tcp local ${toString publicPort}
      '';
      serverStart = pkgs.writeShellScript "macrdp-server-start" ''
        set -euo pipefail
        cfgdir="${config.home.homeDirectory}/.config/macrdp"
        if [[ ! -f "$cfgdir/config.toml" ]]; then
          echo "macrdp: missing $cfgdir/config.toml (HM activation / SecretSpec)" >&2
          exit 1
        fi
        # Prefer ./config.toml (macrdp search order) so TLS certs land here too.
        cd "$cfgdir"
        exec ${lib.getExe macrdp}
      '';
      writeConfigPy = pkgs.writeText "macrdp-write-config.py" ''
        import json, pathlib, sys
        path, user, pw, port = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
        q = json.dumps
        lines = [
            "# Generated by dendritic.apps.macrdp",
            f"port = {port}",
            "width = 0",
            "height = 0",
            "frame_rate = 60",
            'quality = "high_quality"',
            'encoder = "hardware"',
            'chroma_mode = "avc420"',
            'log_level = "info"',
            "idle_timeout_secs = 1800",
        ]
        if pw:
            lines[1:1] = [f"username = {q(user)}", f"password = {q(pw)}"]
        else:
            print(
                "macrdp: WARNING — set pass secretspec/shared/default/MACRDP_PASSWORD",
                file=sys.stderr,
            )
        pathlib.Path(path).write_text("\n".join(lines) + "\n")
      '';
    in
    {
      options.dendritic.apps.macrdp = {
        enable = lib.mkEnableOption "macrdp agent + SecretSpec config.toml";

        listenPort = lib.mkOption {
          type = lib.types.port;
          default = 13389;
        };

        publicPort = lib.mkOption {
          type = lib.types.port;
          default = 3389;
          description = "Port advertised via Bonjour (matches socat forward).";
        };

        bonjourName = lib.mkOption {
          type = lib.types.str;
          default = "mba";
          description = "DNS-SD instance name.";
        };

        username = lib.mkOption {
          type = lib.types.str;
          default = config.home.username;
          description = "RDP NLA username (macrdp config, not macOS login).";
        };

        passwordSecret = lib.mkOption {
          type = lib.types.str;
          default = "MACRDP_PASSWORD";
          description = "SecretSpec key under secretspec/shared/default/.";
        };
      };

      config = lib.mkIf (cfg.enable && pkgs.stdenv.isDarwin) {
        home.packages = [ macrdp ];

        launchd.agents.macrdp = {
          enable = true;
          config = {
            Label = "com.aspaulding.macrdp";
            ProgramArguments = [ "${serverStart}" ];
            RunAtLoad = true;
            KeepAlive = true;
            StandardOutPath = "${config.home.homeDirectory}/.local/state/macrdp/server.log";
            StandardErrorPath = "${config.home.homeDirectory}/.local/state/macrdp/server.err.log";
          };
        };

        launchd.agents.macrdp-bonjour = {
          enable = true;
          config = {
            Label = "com.aspaulding.macrdp-bonjour";
            ProgramArguments = [ "${dnsSd}" ];
            RunAtLoad = true;
            KeepAlive = true;
            StandardOutPath = "${config.home.homeDirectory}/.local/state/macrdp/bonjour.log";
            StandardErrorPath = "${config.home.homeDirectory}/.local/state/macrdp/bonjour.err.log";
          };
        };

        home.activation.macrdpConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          mkdir -p "${config.home.homeDirectory}/.config/macrdp"
          mkdir -p "${config.home.homeDirectory}/.local/state/macrdp"
          _pw="$(${pkgs.secretspec}/bin/secretspec get -f ${secretspecToml} ${cfg.passwordSecret} 2>/dev/null || true)"
          if [[ -z "$_pw" ]]; then
            _pw="$(${pkgs.pass}/bin/pass show secretspec/shared/default/${cfg.passwordSecret} 2>/dev/null || true)"
          fi
          CFG="${config.home.homeDirectory}/.config/macrdp/config.toml"
          umask 077
          ${pkgs.python3}/bin/python3 ${writeConfigPy} "$CFG" "${cfg.username}" "$_pw" "${toString cfg.listenPort}"
          chmod 600 "$CFG" || true
        '';
      };
    };
}
