name: "Auto Release"
on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/checkout@v4"
      - run: |
          COUNT=$(gh release list --limit 1000 | grep -E "^rolling-v0\.1\." | wc -l || echo "0")
          VERSION="rolling-v0.1.$((COUNT + 1))"
          if ! gh release view "$VERSION" >/dev/null 2>&1; then
            gh release create "$VERSION" --title "$VERSION" --prerelease --generate-notes
          else
            echo "Release $VERSION already exists, skipping"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
