name: "Auto Release"
on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/checkout@v4"
      - run: |
          COUNT=1
          while gh release view "v0.1.$COUNT" >/dev/null 2>&1; do
            COUNT=$((COUNT + 1))
          done
          VERSION="v0.1.$COUNT"
          gh release create "$VERSION" --title "$VERSION" --prerelease --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
