on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+*
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cleanup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check initial disk space
        run: |
          echo "=== Initial Disk Space ==="
          df -h
          echo "=== Largest directories ==="
          sudo du -sh /usr/* 2>/dev/null | sort -hr | head -10 || true
      - name: Nothing but Nix
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'
      - name: Check disk space after nothing-but-nix
        run: |
          echo "=== Disk Space After nothing-but-nix ==="
          df -h
          echo "=== Available space on root ==="
          df -h / | tail -1 | awk '{print "Available: " $4}'
  DeterminateCI:
    needs: cleanup-and-build
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: write
      contents: read
