name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v5"
        with:
          persist-credentials: false
      - name: "Set up QEMU for cross-compilation"
        uses: "docker/setup-qemu-action@v3"
        with:
          platforms: "arm64"
      - uses: "DeterminateSystems/determinate-nix-action@v3"
        with:
          extra-conf: |
            extra-platforms = aarch64-linux
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "aspauldingcode/.dotfiles"
          rolling: true
          visibility: "public"
          include-output-paths: true
        env:
          # FlakeHub authentication token
          FLAKEHUB_PUSH_TOKEN: ${{ secrets.FLAKEHUB_PUSH_TOKEN }}
