name: "Publish tags to FlakeHub"
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v5"
        with:
          persist-credentials: false
          ref: "${{ github.event.inputs.tag && format('refs/tags/{0}', github.event.inputs.tag) || '' }}"
      
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      
      - uses: "DeterminateSystems/flakehub-cache-action@main"
      
      - name: "Publish to FlakeHub"
        uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          name: "aspauldingcode/.dotfiles"
          tag: "${{ github.event.inputs.tag || github.ref_name }}"
          include-output-paths: true
        env:
          FLAKEHUB_PUSH_TOKEN: ${{ secrets.FLAKEHUB_PUSH_TOKEN }}