name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v5"
        with:
          persist-credentials: false
      - name: Check initial disk space
        run: |
          echo "=== Initial Disk Space ==="
          df -h
          echo "=== Largest directories ==="
          sudo du -sh /usr/* 2>/dev/null | sort -hr | head -10 || true
      - name: Nothing but Nix
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'rampage'
      - name: Check disk space after nothing-but-nix
        run: |
          echo "=== Disk Space After nothing-but-nix ==="
          df -h
          echo "=== Available space on root ==="
          df -h / | tail -1 | awk '{print "Available: " $4}'
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "aspauldingcode/.dotfiles"
          rolling: true
          visibility: "public"
          include-output-paths: true
